import { useState } from 'react';
import type { Briefing } from '../../types';
import { downloadJSON, copyToClipboard } from '../../utils/helpers';

interface ExportOptionsProps {
  briefing: Briefing | null;
}

export function ExportOptions({ briefing }: ExportOptionsProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  const handleCopyToClipboard = async () => {
    if (!briefing) return;

    const text = `
MORNING BRIEFING - ${new Date(briefing.timestamp).toLocaleDateString()}

EXECUTIVE SUMMARY
${briefing.summary}

KEY FINDINGS (${briefing.keyFindings.length})
${briefing.keyFindings.map((f, i) => `
${i + 1}. ${f.title} [${f.severity.toUpperCase()}]
   ${f.description}
   Confidence: ${f.confidence}%
`).join('\n')}

${briefing.actionItems && briefing.actionItems.length > 0 ? `
ACTION ITEMS
${briefing.actionItems.map((item, i) => `
${i + 1}. [${item.priority.toUpperCase()}] ${item.description}
`).join('\n')}
` : ''}

RECOMMENDATIONS
${briefing.recommendation}

---
Generated by 6:10 Assistant - Ridgeway Intelligence Platform
    `.trim();

    try {
      await copyToClipboard(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleExportJSON = () => {
    if (!briefing) return;
    downloadJSON(briefing, `briefing-${Date.now()}.json`);
  };

  const handleExportPDF = async () => {
    if (!briefing) return;
    
    setExporting(true);

    try {
      const printWindow = window.open('', '_blank', 'width=900,height=700');
      if (!printWindow) {
        throw new Error('Unable to open print window');
      }

      const actionItems = briefing.actionItems && briefing.actionItems.length > 0
        ? `
          <section>
            <h2>Action Items</h2>
            <ul>
              ${briefing.actionItems.map((item) => `
                <li><strong>${item.priority.toUpperCase()}</strong> ${item.description}</li>
              `).join('')}
            </ul>
          </section>
        `
        : '';

      printWindow.document.write(`
        <!doctype html>
        <html>
          <head>
            <title>Morning Briefing</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 32px; color: #111827; }
              h1, h2 { margin-bottom: 12px; }
              h1 { font-size: 28px; }
              h2 { font-size: 18px; margin-top: 28px; }
              p, li { font-size: 14px; line-height: 1.6; }
              .meta { color: #6b7280; margin-bottom: 24px; }
              .finding { border-left: 4px solid #2563eb; padding-left: 12px; margin-bottom: 16px; }
              .badge { display: inline-block; margin-right: 8px; padding: 2px 8px; border-radius: 999px; background: #e5e7eb; font-size: 12px; }
              ul { padding-left: 20px; }
            </style>
          </head>
          <body>
            <h1>Morning Briefing</h1>
            <p class="meta">${new Date(briefing.timestamp).toLocaleString()}</p>

            <section>
              <h2>Executive Summary</h2>
              <p>${briefing.summary.replace(/\n/g, '<br/>')}</p>
            </section>

            <section>
              <h2>Key Findings</h2>
              ${briefing.keyFindings.map((finding) => `
                <div class="finding">
                  <p><strong>${finding.title}</strong></p>
                  <p>${finding.description}</p>
                  <p>
                    <span class="badge">${finding.severity}</span>
                    <span class="badge">${finding.confidence}% confidence</span>
                  </p>
                </div>
              `).join('')}
            </section>

            ${actionItems}

            <section>
              <h2>Recommendations</h2>
              <p>${briefing.recommendation.replace(/\n/g, '<br/>')}</p>
            </section>
          </body>
        </html>
      `);

      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    } catch (error) {
      console.error('Failed to export PDF:', error);
    } finally {
      setExporting(false);
    }
  };

  const handleEmailBriefing = () => {
    if (!briefing) return;

    const subject = `Morning Briefing - ${new Date(briefing.timestamp).toLocaleDateString()}`;
    const body = encodeURIComponent(`
Executive Summary:
${briefing.summary}

Key Findings: ${briefing.keyFindings.length}

Recommendations:
${briefing.recommendation}

[Full briefing attached]
    `.trim());

    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${body}`);
  };

  if (!briefing) {
    return (
      <div className="bg-gray-50 rounded-lg p-6">
        <p className="text-gray-500 text-center">
          Generate a briefing first to export
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-4">
        Export Briefing
      </h3>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Copy to Clipboard */}
        <button
          onClick={handleCopyToClipboard}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 font-medium transition-colors"
        >
          <span className="text-xl">{copied ? '✓' : '📋'}</span>
          <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
        </button>

        {/* Export JSON */}
        <button
          onClick={handleExportJSON}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 font-medium transition-colors"
        >
          <span className="text-xl">💾</span>
          <span>Download JSON</span>
        </button>

        {/* Export PDF */}
        <button
          onClick={handleExportPDF}
          disabled={exporting}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200 font-medium transition-colors disabled:opacity-50"
        >
          <span className="text-xl">{exporting ? '⏳' : '📄'}</span>
          <span>{exporting ? 'Generating...' : 'Export as PDF'}</span>
        </button>

        {/* Email */}
        <button
          onClick={handleEmailBriefing}
          className="flex items-center justify-center space-x-2 px-4 py-3 bg-green-100 text-green-700 rounded-lg hover:bg-green-200 font-medium transition-colors"
        >
          <span className="text-xl">📧</span>
          <span>Email Briefing</span>
        </button>
      </div>

      <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <p className="text-sm text-blue-800">
          <strong>💡 Tip:</strong> Use "Copy to Clipboard" to quickly paste into Slack, email, or documents.
        </p>
      </div>
    </div>
  );
}
